// <auto-generated />
using System;
using System.Collections.Generic;
using Ludeka.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ludeka.Infrastructure.Migrations
{
    [DbContext(typeof(LudekaDbContext))]
    partial class LudekaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ludeka.Core.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Permissions")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Role");

                    b.HasIndex("Status");

                    b.ToTable("AppUsers", (string)null);
                });

            modelBuilder.Entity("Ludeka.Core.Entities.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("EntityType")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("EntityType");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("Ludeka.Core.Entities.BoardGameEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsOfficial")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Organizer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Country");

                    b.HasIndex("IsOfficial");

                    b.HasIndex("StartDate");

                    b.ToTable("BoardGameEvents", (string)null);
                });

            modelBuilder.Entity("Ludeka.Core.Entities.CommunityNotificationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("text");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Channel");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.ToTable("NotificationLogs", (string)null);
                });

            modelBuilder.Entity("Ludeka.Core.Entities.Creator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<int?>("BggPersonId")
                        .HasColumnType("integer");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nationality")
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Creators", (string)null);
                });

            modelBuilder.Entity("Ludeka.Core.Entities.ExpansionRecipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaseGameId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdealFor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<Guid>>("IncludedExpansionIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BaseGameId");

                    b.ToTable("ExpansionRecipes", (string)null);
                });

            modelBuilder.Entity("Ludeka.Core.Entities.ExpansionSynergy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaseGameId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExpansionAId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExpansionBId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BaseGameId");

                    b.HasIndex("ExpansionBId");

                    b.HasIndex("ExpansionAId", "ExpansionBId");

                    b.ToTable("ExpansionSynergies", (string)null);
                });

            modelBuilder.Entity("Ludeka.Core.Entities.FoundingVerdict", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuthorUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FamilyVerdict")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("OverallVerdict")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Recommendation")
                        .HasColumnType("integer");

                    b.Property<string>("TwoPlayerVerdict")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.ToTable("FoundingVerdicts", (string)null);
                });

            modelBuilder.Entity("Ludeka.Core.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BaseGameId")
                        .HasColumnType("uuid");

                    b.Property<int>("BggId")
                        .HasColumnType("integer");

                    b.Property<int?>("BggRank")
                        .HasColumnType("integer");

                    b.Property<double>("BggRating")
                        .HasColumnType("double precision");

                    b.Property<int>("Confrontation")
                        .HasColumnType("integer");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Designer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ExpansionNecessity")
                        .HasColumnType("integer");

                    b.Property<int?>("ExtraDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("ExtraPlayerCount")
                        .HasColumnType("integer");

                    b.Property<int>("Footprint")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("ImpactTags")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<bool>("IsOfficialSolo")
                        .HasColumnType("boolean");

                    b.Property<int>("Language")
                        .HasColumnType("integer");

                    b.Property<double>("LudistRating")
                        .HasColumnType("double precision");

                    b.Property<string>("OriginalTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpanishTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Style")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("WhatItBringsSummary")
                        .HasColumnType("text");

                    b.Property<int>("YearPublished")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Age", "Ludeka.Core.Entities.Game.Age#AgeRating", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("BoxAge")
                                .HasColumnType("integer");

                            b1.Property<int>("CommunityAge")
                                .HasColumnType("integer");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Duration", "Ludeka.Core.Entities.Game.Duration#GameDuration", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("EstimatedPerPlayerMinutes")
                                .HasColumnType("integer");

                            b1.Property<int>("MaxMinutes")
                                .HasColumnType("integer");

                            b1.Property<int>("MinMinutes")
                                .HasColumnType("integer");
                        });

                    b.HasKey("Id");

                    b.HasIndex("BaseGameId");

                    b.HasIndex("BggId")
                        .IsUnique();

                    b.HasIndex("OriginalTitle");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("SpanishTitle");

                    b.HasIndex("Type");

                    b.ToTable("Games", (string)null);
                });

            modelBuilder.Entity("Ludeka.Core.Entities.GameEditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssociatedReportId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EditedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EditorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EditorUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("SummaryOfChanges")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("EditedAt");

                    b.HasIndex("GameId");

                    b.ToTable("GameEditLogs", (string)null);
                });

            modelBuilder.Entity("Ludeka.Core.Entities.GameIssueReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("GameSlug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GameTitle")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("IssueType")
                        .HasColumnType("integer");

                    b.Property<string>("ModeratorNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ReportedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ReporterNameOrAlias")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResolvedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("GameId");

                    b.HasIndex("IssueType");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("GameIssueReports", (string)null);
                });

            modelBuilder.Entity("Ludeka.Core.Entities.GameLoan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BorrowerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsReturned")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LoanDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ReturnedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId", "GameId");

                    b.HasIndex("UserId", "IsReturned");

                    b.ToTable("GameLoans", (string)null);
                });

            modelBuilder.Entity("Ludeka.Core.Entities.GamePlayLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTimeOffset>("PlayDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlayerCount")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId", "PlayDate");

                    b.ToTable("GamePlayLogs", (string)null);
                });

            modelBuilder.Entity("Ludeka.Core.Entities.Giveaway", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Collaborator")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DeadlineAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("GameTitle")
                        .HasColumnType("text");

                    b.Property<string>("InstagramMediaId")
                        .HasColumnType("text");

                    b.Property<string>("InstagramPermalink")
                        .HasColumnType("text");

                    b.Property<bool>("IsCommunityExclusive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPromoted")
                        .HasColumnType("boolean");

                    b.Property<string>("Organizer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Country");

                    b.HasIndex("DeadlineAt");

                    b.HasIndex("GameId");

                    b.HasIndex("IsCommunityExclusive");

                    b.HasIndex("Platform");

                    b.ToTable("Giveaways", (string)null);
                });

            modelBuilder.Entity("Ludeka.Core.Entities.InstagramPostDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CreatedByUserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("InstagramMediaId")
                        .HasColumnType("text");

                    b.Property<string>("InstagramPermalink")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SvgContent")
                        .HasColumnType("text");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("SourceType", "SourceId");

                    b.ToTable("InstagramPostDrafts", (string)null);
                });

            modelBuilder.Entity("Ludeka.Core.Entities.MediaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorChannel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("EmbedUrl")
                        .HasColumnType("text");

                    b.Property<string>("Excerpt")
                        .HasColumnType("text");

                    b.Property<Guid?>("GameId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsBroken")
                        .HasColumnType("boolean");

                    b.Property<int?>("LikesCount")
                        .HasColumnType("integer");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<string>("PlayerCountBadge")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("GameId");

                    b.HasIndex("Platform");

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.HasIndex("GameId", "Status");

                    b.ToTable("MediaItems", (string)null);
                });

            modelBuilder.Entity("Ludeka.Core.Entities.NightlyCatalogingExecutionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CatalogedTitlesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer");

                    b.Property<int>("NewsDiscoveryCount")
                        .HasColumnType("integer");

                    b.Property<int>("QueueProcessedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TopBackfillCount")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCatalogedCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.ToTable("NightlyCatalogingExecutionLogs", (string)null);
                });

            modelBuilder.Entity("Ludeka.Core.Entities.PendingBggImport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BggId")
                        .HasColumnType("integer");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("ExtractedTitle")
                        .HasColumnType("text");

                    b.Property<int>("Origin")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RequestedCount")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("YearPublished")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BggId")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status", "RequestedCount");

                    b.ToTable("PendingBggImports", (string)null);
                });

            modelBuilder.Entity("Ludeka.Core.Entities.Publisher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Publishers", (string)null);
                });

            modelBuilder.Entity("Ludeka.Core.Entities.RuleAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("boolean");

                    b.Property<string>("OfficialRuleReference")
                        .HasColumnType("text");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VotesCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsAccepted");

                    b.HasIndex("QuestionId");

                    b.ToTable("RuleAnswers", (string)null);
                });

            modelBuilder.Entity("Ludeka.Core.Entities.RuleQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AcceptedAnswerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VotesCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("GameId");

                    b.ToTable("RuleQuestions", (string)null);
                });

            modelBuilder.Entity("Ludeka.Core.Entities.RuleVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnswerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "AnswerId");

                    b.HasIndex("UserId", "QuestionId");

                    b.ToTable("RuleVotes", (string)null);
                });

            modelBuilder.Entity("Ludeka.Core.Entities.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("AffiliateCode")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("HasLoyaltyProgram")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.PrimitiveCollection<List<string>>("ShippingCountries")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Country");

                    b.HasIndex("Name");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Stores", (string)null);
                });

            modelBuilder.Entity("Ludeka.Core.Entities.UserCollectionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("BggId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("GameId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPlayed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("PendingThumbnailUrl")
                        .HasColumnType("text");

                    b.Property<string>("PendingTitle")
                        .HasColumnType("text");

                    b.Property<int?>("PendingYearPublished")
                        .HasColumnType("integer");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId", "BggId");

                    b.HasIndex("UserId", "GameId");

                    b.HasIndex("UserId", "IsPlayed");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("UserCollectionItems", (string)null);
                });

            modelBuilder.Entity("Ludeka.Core.Entities.UserGameReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("MicroReview")
                        .HasColumnType("text");

                    b.Property<int?>("PlayContext")
                        .HasColumnType("integer");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId", "GameId")
                        .IsUnique();

                    b.ToTable("UserGameReviews", (string)null);
                });

            modelBuilder.Entity("Ludeka.Core.Entities.UserPreference", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PreferredTheme")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("UserPreferences", (string)null);
                });

            modelBuilder.Entity("Ludeka.Core.Entities.WeeklyRelease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("EstimatedPvp")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("InstagramMediaId")
                        .HasColumnType("text");

                    b.Property<string>("InstagramPermalink")
                        .HasColumnType("text");

                    b.Property<bool>("IsReprint")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("ReleaseDate");

                    b.ToTable("WeeklyReleases", (string)null);
                });

            modelBuilder.Entity("Ludeka.Core.Entities.AuditLogEntry", b =>
                {
                    b.OwnsMany("Ludeka.Core.ValueObjects.AuditFieldChange", "Changes", b1 =>
                        {
                            b1.Property<Guid>("AuditLogEntryId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("FieldName")
                                .IsRequired();

                            b1.Property<string>("NewValue");

                            b1.Property<string>("OldValue");

                            b1.HasKey("AuditLogEntryId", "__synthesizedOrdinal");

                            b1.ToTable("AuditLogs");

                            b1.ToJson("Changes");

                            b1.WithOwner()
                                .HasForeignKey("AuditLogEntryId");
                        });

                    b.Navigation("Changes");
                });

            modelBuilder.Entity("Ludeka.Core.Entities.Creator", b =>
                {
                    b.OwnsMany("Ludeka.Core.ValueObjects.SocialNetworkLink", "SocialLinks", b1 =>
                        {
                            b1.Property<Guid>("CreatorId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Handle");

                            b1.Property<int>("Platform");

                            b1.Property<string>("Title");

                            b1.Property<string>("Url")
                                .IsRequired();

                            b1.HasKey("CreatorId", "__synthesizedOrdinal");

                            b1.ToTable("Creators");

                            b1.ToJson("SocialLinks");

                            b1.WithOwner()
                                .HasForeignKey("CreatorId");
                        });

                    b.Navigation("SocialLinks");
                });

            modelBuilder.Entity("Ludeka.Core.Entities.ExpansionRecipe", b =>
                {
                    b.HasOne("Ludeka.Core.Entities.Game", "BaseGame")
                        .WithMany()
                        .HasForeignKey("BaseGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseGame");
                });

            modelBuilder.Entity("Ludeka.Core.Entities.ExpansionSynergy", b =>
                {
                    b.HasOne("Ludeka.Core.Entities.Game", "BaseGame")
                        .WithMany()
                        .HasForeignKey("BaseGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ludeka.Core.Entities.Game", "ExpansionA")
                        .WithMany()
                        .HasForeignKey("ExpansionAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ludeka.Core.Entities.Game", "ExpansionB")
                        .WithMany()
                        .HasForeignKey("ExpansionBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseGame");

                    b.Navigation("ExpansionA");

                    b.Navigation("ExpansionB");
                });

            modelBuilder.Entity("Ludeka.Core.Entities.FoundingVerdict", b =>
                {
                    b.OwnsMany("Ludeka.Core.ValueObjects.FoundingPhoto", "Photos", b1 =>
                        {
                            b1.Property<Guid>("FoundingVerdictId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Caption")
                                .IsRequired();

                            b1.Property<string>("PhotoUrl")
                                .IsRequired();

                            b1.HasKey("FoundingVerdictId", "__synthesizedOrdinal");

                            b1.ToTable("FoundingVerdicts");

                            b1.ToJson("Photos");

                            b1.WithOwner()
                                .HasForeignKey("FoundingVerdictId");
                        });

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Ludeka.Core.Entities.Game", b =>
                {
                    b.HasOne("Ludeka.Core.Entities.Game", "BaseGame")
                        .WithMany("Expansions")
                        .HasForeignKey("BaseGameId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Ludeka.Core.ValueObjects.AiGameSummary", "AiSummary", b1 =>
                        {
                            b1.Property<Guid>("GameId");

                            b1.Property<string>("AgeSummary")
                                .IsRequired();

                            b1.Property<string>("FootprintSummary")
                                .IsRequired();

                            b1.Property<string>("GeneralVerdict")
                                .IsRequired();

                            b1.Property<DateTime>("GeneratedAt");

                            b1.Property<string>("Model")
                                .IsRequired();

                            b1.Property<string>("ScalabilitySummary")
                                .IsRequired();

                            b1.HasKey("GameId");

                            b1.ToTable("Games");

                            b1.ToJson("AiSummary");

                            b1.WithOwner()
                                .HasForeignKey("GameId");
                        });

                    b.OwnsMany("Ludeka.Core.ValueObjects.GamePurchaseLink", "PurchaseLinks", b1 =>
                        {
                            b1.Property<Guid>("GameId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("AffiliateTag");

                            b1.Property<string>("AffiliateUrl")
                                .IsRequired();

                            b1.Property<string>("Badge");

                            b1.Property<string>("Country")
                                .IsRequired();

                            b1.Property<string>("Currency")
                                .IsRequired();

                            b1.Property<bool>("InStock");

                            b1.Property<decimal?>("Price");

                            b1.PrimitiveCollection<string>("ShippingCountries");

                            b1.Property<string>("StoreName")
                                .IsRequired();

                            b1.HasKey("GameId", "__synthesizedOrdinal");

                            b1.ToTable("Games");

                            b1.ToJson("PurchaseLinks");

                            b1.WithOwner()
                                .HasForeignKey("GameId");
                        });

                    b.OwnsMany("Ludeka.Core.ValueObjects.ScalabilityEntry", "Scalability", b1 =>
                        {
                            b1.Property<Guid>("GameId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("BestVotes");

                            b1.Property<string>("DisplayCount")
                                .IsRequired();

                            b1.Property<int>("NotRecommendedVotes");

                            b1.Property<int>("PlayerCount");

                            b1.Property<int>("RecommendedVotes");

                            b1.Property<int>("Status");

                            b1.HasKey("GameId", "__synthesizedOrdinal");

                            b1.ToTable("Games");

                            b1.ToJson("Scalability");

                            b1.WithOwner()
                                .HasForeignKey("GameId");
                        });

                    b.OwnsMany("Ludeka.Core.ValueObjects.SleeveItem", "Sleeves", b1 =>
                        {
                            b1.Property<Guid>("GameId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("AffiliateUrl");

                            b1.Property<int>("CardCount");

                            b1.Property<string>("Country");

                            b1.Property<string>("FormatName")
                                .IsRequired();

                            b1.Property<double>("HeightMm");

                            b1.PrimitiveCollection<string>("ShippingCountries");

                            b1.Property<string>("StoreName");

                            b1.Property<double>("WidthMm");

                            b1.HasKey("GameId", "__synthesizedOrdinal");

                            b1.ToTable("Games");

                            b1.ToJson("Sleeves");

                            b1.WithOwner()
                                .HasForeignKey("GameId");
                        });

                    b.Navigation("AiSummary");

                    b.Navigation("BaseGame");

                    b.Navigation("PurchaseLinks");

                    b.Navigation("Scalability");

                    b.Navigation("Sleeves");
                });

            modelBuilder.Entity("Ludeka.Core.Entities.GameLoan", b =>
                {
                    b.HasOne("Ludeka.Core.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Ludeka.Core.Entities.GamePlayLog", b =>
                {
                    b.HasOne("Ludeka.Core.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Ludeka.Core.Entities.Giveaway", b =>
                {
                    b.HasOne("Ludeka.Core.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Ludeka.Core.Entities.MediaItem", b =>
                {
                    b.HasOne("Ludeka.Core.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Ludeka.Core.Entities.Publisher", b =>
                {
                    b.OwnsMany("Ludeka.Core.ValueObjects.SocialNetworkLink", "SocialLinks", b1 =>
                        {
                            b1.Property<Guid>("PublisherId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Handle");

                            b1.Property<int>("Platform");

                            b1.Property<string>("Title");

                            b1.Property<string>("Url")
                                .IsRequired();

                            b1.HasKey("PublisherId", "__synthesizedOrdinal");

                            b1.ToTable("Publishers");

                            b1.ToJson("SocialLinks");

                            b1.WithOwner()
                                .HasForeignKey("PublisherId");
                        });

                    b.Navigation("SocialLinks");
                });

            modelBuilder.Entity("Ludeka.Core.Entities.RuleAnswer", b =>
                {
                    b.HasOne("Ludeka.Core.Entities.RuleQuestion", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Ludeka.Core.Entities.RuleQuestion", b =>
                {
                    b.HasOne("Ludeka.Core.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Ludeka.Core.Entities.Store", b =>
                {
                    b.OwnsMany("Ludeka.Core.ValueObjects.SocialNetworkLink", "SocialLinks", b1 =>
                        {
                            b1.Property<Guid>("StoreId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Handle");

                            b1.Property<int>("Platform");

                            b1.Property<string>("Title");

                            b1.Property<string>("Url")
                                .IsRequired();

                            b1.HasKey("StoreId", "__synthesizedOrdinal");

                            b1.ToTable("Stores");

                            b1.ToJson("SocialLinks");

                            b1.WithOwner()
                                .HasForeignKey("StoreId");
                        });

                    b.Navigation("SocialLinks");
                });

            modelBuilder.Entity("Ludeka.Core.Entities.UserCollectionItem", b =>
                {
                    b.HasOne("Ludeka.Core.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Ludeka.Core.Entities.UserGameReview", b =>
                {
                    b.HasOne("Ludeka.Core.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Ludeka.Core.ValueObjects.UserFamilyExperienceVote", "FamilyExperience", b1 =>
                        {
                            b1.Property<Guid>("UserGameReviewId");

                            b1.Property<bool>("IsAdaptedRules");

                            b1.Property<bool>("PlayedWithChildren");

                            b1.Property<int?>("SuggestedMinAge");

                            b1.HasKey("UserGameReviewId");

                            b1.ToTable("UserGameReviews");

                            b1.ToJson("FamilyExperience");

                            b1.WithOwner()
                                .HasForeignKey("UserGameReviewId");
                        });

                    b.OwnsMany("Ludeka.Core.ValueObjects.UserPlayerCountVote", "PlayerCountRatings", b1 =>
                        {
                            b1.Property<Guid>("UserGameReviewId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("PlayerCount");

                            b1.Property<int>("Status");

                            b1.HasKey("UserGameReviewId", "__synthesizedOrdinal");

                            b1.ToTable("UserGameReviews");

                            b1.ToJson("PlayerCountRatings");

                            b1.WithOwner()
                                .HasForeignKey("UserGameReviewId");
                        });

                    b.Navigation("FamilyExperience");

                    b.Navigation("Game");

                    b.Navigation("PlayerCountRatings");
                });

            modelBuilder.Entity("Ludeka.Core.Entities.WeeklyRelease", b =>
                {
                    b.HasOne("Ludeka.Core.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Ludeka.Core.Entities.Game", b =>
                {
                    b.Navigation("Expansions");
                });

            modelBuilder.Entity("Ludeka.Core.Entities.RuleQuestion", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
